/* This is a translation of .\ctf.bf, generated by bftoc.py (by Paul Kaefer)
 * It was generated on Sunday, October 01, 2023 at 10:45AM
 */

#include <stdio.h>

int main() {
    int size = 1000;
    int tape[1000];
    int i = 0;

    /* Clearing the tape (array) */
    for (i = 0; i < size; i++)
        tape[i] = 0;

    int ptr = 0;

    ptr += 1;
    tape[ptr] += 9;
    while (tape[ptr] != 0) {
        ptr -= 1;
        tape[ptr] += 10;
        ptr += 1;
        tape[ptr] -= 1;
    }
    ptr -= 1;
    tape[ptr] += 9;
    ptr += 2;
    tape[ptr] += 4;
    while (tape[ptr] != 0) {
        ptr -= 1;
        tape[ptr] += 10;
        ptr += 1;
        tape[ptr] -= 1;
    }
    ptr -= 1;
    tape[ptr] += 6;
    ptr += 3;
    tape[ptr] += 9;
    while (tape[ptr] != 0) {
        ptr -= 1;
        tape[ptr] += 10;
        ptr += 1;
        tape[ptr] -= 1;
    }
    ptr -= 1;
    tape[ptr] += 7;
    ptr -= 3;
    while (tape[ptr] != 0) {
        ptr += 4;
        tape[ptr] += 1;
        ptr += 1;
        tape[ptr] += 1;
        ptr -= 5;
        tape[ptr] -= 1;
    }
    ptr += 5;
    while (tape[ptr] != 0) {
        ptr -= 5;
        tape[ptr] += 1;
        ptr += 5;
        tape[ptr] -= 1;
    }
    ptr += 1;
    tape[ptr] += 1;
    ptr -= 3;
    while (tape[ptr] != 0) {
        ptr += 2;
        tape[ptr] += 1;
        ptr -= 2;
        tape[ptr] -= 1;
    }
    ptr += 2;
    while (tape[ptr] != 0) {
        ptr += 1;
        tape[ptr] -= 1;
    }
    ptr += 1;
    while (tape[ptr] != 0) {
        ptr += 1;
        ptr -= 4;
        tape[ptr] += 1;
        ptr += 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr += 2;
        tape[ptr] -= 1;
        ptr += 1;
    }
    ptr -= 1;
    tape[ptr] += 1;
    ptr -= 2;
    while (tape[ptr] != 0) {
        ptr += 1;
        tape[ptr] -= 1;
        while (tape[ptr] != 0) {
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr += 1;
        while (tape[ptr] != 0) {
            ptr += 1;
            ptr -= 4;
            tape[ptr] += 1;
            ptr += 1;
            while (tape[ptr] != 0) {
                tape[ptr] -= 1;
            }
            tape[ptr] += 1;
            ptr += 2;
            tape[ptr] -= 1;
            ptr += 1;
        }
        ptr -= 1;
        tape[ptr] += 1;
        ptr -= 2;
        tape[ptr] -= 1;
    }
    ptr += 1;
    while (tape[ptr] != 0) {
        tape[ptr] -= 1;
    }
    ptr += 1;
    tape[ptr] -= 1;
    ptr -= 6;
    while (tape[ptr] != 0) {
        ptr += 4;
        tape[ptr] += 1;
        ptr += 1;
        tape[ptr] += 1;
        ptr -= 5;
        tape[ptr] -= 1;
    }
    ptr += 5;
    while (tape[ptr] != 0) {
        ptr -= 5;
        tape[ptr] += 1;
        ptr += 5;
        tape[ptr] -= 1;
    }
    ptr += 1;
    tape[ptr] += 12;
    while (tape[ptr] != 0) {
        ptr -= 1;
        tape[ptr] += 10;
        ptr += 1;
        tape[ptr] -= 1;
    }
    ptr -= 1;
    tape[ptr] += 2;
    ptr += 2;
    tape[ptr] += 1;
    ptr -= 3;
    while (tape[ptr] != 0) {
        ptr += 2;
        tape[ptr] += 1;
        ptr -= 2;
        tape[ptr] -= 1;
    }
    ptr += 2;
    while (tape[ptr] != 0) {
        ptr += 1;
        tape[ptr] -= 1;
    }
    ptr += 1;
    while (tape[ptr] != 0) {
        ptr += 1;
        ptr -= 4;
        tape[ptr] += 1;
        ptr += 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr += 2;
        tape[ptr] -= 1;
        ptr += 1;
    }
    ptr -= 1;
    tape[ptr] += 1;
    ptr -= 2;
    while (tape[ptr] != 0) {
        ptr += 1;
        tape[ptr] -= 1;
        while (tape[ptr] != 0) {
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr += 1;
        while (tape[ptr] != 0) {
            ptr += 1;
            ptr -= 4;
            tape[ptr] += 1;
            ptr += 1;
            while (tape[ptr] != 0) {
                tape[ptr] -= 1;
            }
            tape[ptr] += 1;
            ptr += 2;
            tape[ptr] -= 1;
            ptr += 1;
        }
        ptr -= 1;
        tape[ptr] += 1;
        ptr -= 2;
        tape[ptr] -= 1;
    }
    ptr += 1;
    while (tape[ptr] != 0) {
        tape[ptr] -= 1;
    }
    ptr += 1;
    tape[ptr] -= 1;
    ptr -= 4;
    while (tape[ptr] != 0) {
        ptr += 3;
        tape[ptr] += 1;
        ptr -= 3;
        tape[ptr] -= 1;
    }
    ptr += 3;
    while (tape[ptr] != 0) {
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 2;
        while (tape[ptr] != 0) {
            ptr += 2;
            tape[ptr] += 1;
            ptr -= 1;
            tape[ptr] += 1;
            ptr -= 1;
            tape[ptr] -= 1;
        }
        ptr += 1;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 1;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr += 1;
        while (tape[ptr] != 0) {
            ptr -= 3;
            tape[ptr] += 1;
            ptr += 3;
            while (tape[ptr] != 0) {
                tape[ptr] -= 1;
            }
        }
    }
    ptr -= 2;
    while (tape[ptr] != 0) {
        tape[ptr] -= 1;
    }
    ptr -= 2;
    while (tape[ptr] != 0) {
        tape[ptr] -= 1;
    }
    ptr += 1;
    while (tape[ptr] != 0) {
        ptr -= 1;
        tape[ptr] += 1;
        ptr += 1;
        tape[ptr] -= 1;
    }
    ptr -= 1;
    while (tape[ptr] != 0) {
        ptr += 1;
        tape[ptr] += 1;
        ptr += 1;
        tape[ptr] += 1;
        ptr -= 2;
        tape[ptr] -= 1;
    }
    ptr += 2;
    while (tape[ptr] != 0) {
        ptr -= 2;
        tape[ptr] += 1;
        ptr += 2;
        tape[ptr] -= 1;
    }
    tape[ptr] += 1;
    ptr -= 1;
    tape[3] = 0;
    while (tape[ptr] != 0) {
        ptr += 6;
        tape[ptr] += 10;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 1;
        ptr += 3;
        tape[ptr] += 11;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 4;
        ptr += 3;
        tape[ptr] += 11;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 4;
        ptr += 3;
        tape[ptr] += 11;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 1;
        ptr += 3;
        tape[ptr] += 11;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 4;
        ptr += 5;
        tape[ptr] += 1;
        while (tape[ptr] != 0) {
            ptr -= 1;
            while (tape[ptr] != 0) {
                ptr += 3;
                tape[ptr] += 1;
                ptr += 1;
                tape[ptr] += 1;
                ptr -= 4;
                tape[ptr] -= 1;
            }
            ptr += 4;
            while (tape[ptr] != 0) {
                ptr -= 4;
                tape[ptr] += 1;
                ptr += 4;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0) {
                ptr -= 16;
                tape[ptr] += 1;
                ptr += 16;
                tape[ptr] -= 1;
            }
            ptr -= 18;
            ptr += 2;
            while (tape[ptr] != 0) {
                while (tape[ptr] != 0) {
                    ptr += 2;
                }
                tape[ptr] += 1;
                while (tape[ptr] != 0) {
                    ptr -= 2;
                }
                ptr += 2;
                tape[ptr] -= 1;
            }
            tape[ptr] += 1;
            while (tape[ptr] != 0) {
                ptr += 2;
            }
            ptr -= 1;
            while (tape[ptr] != 0) {
                ptr -= 1;
                while (tape[ptr] != 0) {
                    ptr -= 2;
                }
                ptr += 1;
                tape[ptr] += 1;
                ptr -= 1;
                ptr += 17;
                tape[ptr] += 1;
                ptr -= 17;
                ptr += 2;
                while (tape[ptr] != 0) {
                    ptr += 2;
                }
                ptr -= 1;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0) {
                ptr -= 2;
            }
            ptr += 1;
            while (tape[ptr] != 0) {
                ptr += 1;
                while (tape[ptr] != 0) {
                    ptr += 2;
                }
                ptr -= 1;
                tape[ptr] += 1;
                ptr -= 1;
                while (tape[ptr] != 0) {
                    ptr -= 2;
                }
                ptr += 1;
                tape[ptr] -= 1;
            }
            ptr += 1;
            while (tape[ptr] != 0) {
                ptr += 2;
            }
            ptr -= 2;
            while (tape[ptr] != 0) {
                tape[ptr] -= 1;
                ptr -= 2;
            }
            ptr += 18;
            ptr -= 1;
            while (tape[ptr] != 0) {
                tape[ptr] -= 1;
                ptr += 1;
                tape[ptr] -= 1;
                ptr -= 1;
            }
            tape[ptr] += 1;
            ptr += 1;
            while (tape[ptr] != 0) {
                ptr -= 1;
                tape[ptr] -= 1;
                ptr += 1;
                while (tape[ptr] != 0) {
                    tape[ptr] -= 1;
                }
            }
            ptr -= 1;
            while (tape[ptr] != 0) {
                ptr += 1;
                tape[ptr] += 1;
                ptr -= 1;
                while (tape[ptr] != 0) {
                    tape[ptr] -= 1;
                }
            }
            tape[ptr] += 1;
            ptr += 1;
            while (tape[ptr] != 0) {
                ptr -= 1;
                tape[ptr] -= 1;
                ptr += 1;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0) {
                ptr -= 2;
                while (tape[ptr] != 0) {
                    ptr += 4;
                    tape[ptr] += 1;
                    ptr += 1;
                    tape[ptr] += 1;
                    ptr -= 5;
                    tape[ptr] -= 1;
                }
                ptr += 5;
                while (tape[ptr] != 0) {
                    ptr -= 5;
                    tape[ptr] += 1;
                    ptr += 5;
                    tape[ptr] -= 1;
                }
                ptr -= 1;
                while (tape[ptr] != 0) {
                    ptr -= 17;
                    tape[ptr] += 1;
                    ptr += 17;
                    tape[ptr] -= 1;
                }
                ptr -= 19;
                ptr += 2;
                while (tape[ptr] != 0) {
                    while (tape[ptr] != 0) {
                        ptr += 2;
                    }
                    tape[ptr] += 1;
                    while (tape[ptr] != 0) {
                        ptr -= 2;
                    }
                    ptr += 2;
                    tape[ptr] -= 1;
                }
                tape[ptr] += 1;
                while (tape[ptr] != 0) {
                    ptr += 2;
                }
                ptr -= 1;
                while (tape[ptr] != 0) {
                    ptr -= 1;
                    while (tape[ptr] != 0) {
                        ptr -= 2;
                    }
                    ptr += 1;
                    tape[ptr] += 1;
                    ptr -= 1;
                    ptr += 18;
                    tape[ptr] += 1;
                    ptr -= 18;
                    ptr += 2;
                    while (tape[ptr] != 0) {
                        ptr += 2;
                    }
                    ptr -= 1;
                    tape[ptr] -= 1;
                }
                ptr -= 1;
                while (tape[ptr] != 0) {
                    ptr -= 2;
                }
                ptr += 1;
                while (tape[ptr] != 0) {
                    ptr += 1;
                    while (tape[ptr] != 0) {
                        ptr += 2;
                    }
                    ptr -= 1;
                    tape[ptr] += 1;
                    ptr -= 1;
                    while (tape[ptr] != 0) {
                        ptr -= 2;
                    }
                    ptr += 1;
                    tape[ptr] -= 1;
                }
                ptr += 1;
                while (tape[ptr] != 0) {
                    ptr += 2;
                }
                ptr -= 2;
                while (tape[ptr] != 0) {
                    tape[ptr] -= 1;
                    ptr -= 2;
                }
                ptr += 18;
                printf("%c", tape[ptr]); // 1
                while (tape[ptr] != 0) {
                    tape[ptr] -= 1;
                }
                ptr -= 3;
                while (tape[ptr] != 0) {
                    ptr += 3;
                    tape[ptr] += 1;
                    ptr += 1;
                    tape[ptr] += 1;
                    ptr -= 4;
                    tape[ptr] -= 1;
                }
                ptr += 4;
                while (tape[ptr] != 0) {
                    ptr -= 4;
                    tape[ptr] += 1;
                    ptr += 4;
                    tape[ptr] -= 1;
                }
                tape[ptr] += 1;
                while (tape[ptr] != 0) {
                    ptr -= 1;
                    tape[ptr] += 1;
                    ptr += 1;
                    tape[ptr] -= 1;
                }
                ptr -= 4;
                while (tape[ptr] != 0) {
                    tape[ptr] -= 1;
                }
                ptr += 3;
                while (tape[ptr] != 0) {
                    ptr -= 3;
                    tape[ptr] += 1;
                    ptr += 3;
                    tape[ptr] -= 1;
                }
                ptr -= 1;
                while (tape[ptr] != 0) {
                    tape[ptr] -= 1;
                }
                ptr -= 1;
                tape[ptr] += 1;
                ptr += 1;
            }
            ptr -= 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] -= 1;
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
    }
    ptr += 1;
    while (tape[ptr] != 0) {
        ptr += 5;
        tape[ptr] += 10;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 2;
        ptr += 3;
        tape[ptr] += 10;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 8;
        ptr += 3;
        tape[ptr] += 9;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 7;
        ptr += 3;
        tape[ptr] += 10;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 3;
        ptr += 3;
        tape[ptr] += 12;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 3;
        ptr += 3;
        tape[ptr] += 9;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 8;
        ptr += 3;
        tape[ptr] += 11;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 4;
        ptr += 3;
        tape[ptr] += 9;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 7;
        ptr += 3;
        tape[ptr] += 10;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 5;
        ptr += 3;
        tape[ptr] += 11;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        ptr += 3;
        tape[ptr] += 10;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 2;
        ptr += 3;
        tape[ptr] += 11;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 7;
        ptr += 3;
        tape[ptr] += 9;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 9;
        ptr += 3;
        tape[ptr] += 10;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 7;
        ptr += 3;
        tape[ptr] += 9;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 5;
        ptr += 3;
        tape[ptr] += 10;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 5;
        ptr += 3;
        tape[ptr] += 11;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 5;
        ptr += 3;
        tape[ptr] += 9;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 5;
        ptr += 3;
        tape[ptr] += 9;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 8;
        ptr += 3;
        tape[ptr] += 9;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 7;
        ptr += 3;
        tape[ptr] += 11;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 5;
        ptr += 3;
        tape[ptr] += 10;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 1;
        ptr += 3;
        tape[ptr] += 10;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        ptr += 3;
        tape[ptr] += 9;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 5;
        ptr += 3;
        tape[ptr] += 11;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 1;
        ptr += 3;
        tape[ptr] += 11;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        ptr += 3;
        tape[ptr] += 9;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 5;
        ptr += 3;
        tape[ptr] += 11;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 5;
        ptr += 3;
        tape[ptr] += 11;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 6;
        ptr += 3;
        tape[ptr] += 9;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 7;
        ptr += 3;
        tape[ptr] += 9;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 9;
        ptr += 3;
        tape[ptr] += 10;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 7;
        ptr += 3;
        tape[ptr] += 3;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 3;
        ptr += 3;
        tape[ptr] += 12;
        while (tape[ptr] != 0) {
            ptr -= 1;
            tape[ptr] += 10;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 5;
        ptr += 5;
        tape[ptr] += 1;
        while (tape[ptr] != 0) {
            ptr -= 1;
            while (tape[ptr] != 0) {
                ptr += 3;
                tape[ptr] += 1;
                ptr += 1;
                tape[ptr] += 1;
                ptr -= 4;
                tape[ptr] -= 1;
            }
            ptr += 4;
            while (tape[ptr] != 0) {
                ptr -= 4;
                tape[ptr] += 1;
                ptr += 4;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0) {
                ptr -= 74;
                tape[ptr] += 1;
                ptr += 74;
                tape[ptr] -= 1;
            }
            ptr -= 76;
            ptr += 2;
            while (tape[ptr] != 0) {
                while (tape[ptr] != 0) {
                    ptr += 2;
                }
                tape[ptr] += 1;
                while (tape[ptr] != 0) {
                    ptr -= 2;
                }
                ptr += 2;
                tape[ptr] -= 1;
            }
            tape[ptr] += 1;
            while (tape[ptr] != 0) {
                ptr += 2;
            }
            ptr -= 1;
            while (tape[ptr] != 0) {
                ptr -= 1;
                while (tape[ptr] != 0) {
                    ptr -= 2;
                }
                ptr += 1;
                tape[ptr] += 1;
                ptr -= 1;
                ptr += 75;
                tape[ptr] += 1;
                ptr -= 75;
                ptr += 2;
                while (tape[ptr] != 0) {
                    ptr += 2;
                }
                ptr -= 1;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0) {
                ptr -= 2;
            }
            ptr += 1;
            while (tape[ptr] != 0) {
                ptr += 1;
                while (tape[ptr] != 0) {
                    ptr += 2;
                }
                ptr -= 1;
                tape[ptr] += 1;
                ptr -= 1;
                while (tape[ptr] != 0) {
                    ptr -= 2;
                }
                ptr += 1;
                tape[ptr] -= 1;
            }
            ptr += 1;
            while (tape[ptr] != 0) {
                ptr += 2;
            }
            ptr -= 2;
            while (tape[ptr] != 0) {
                tape[ptr] -= 1;
                ptr -= 2;
            }
            ptr += 76;
            ptr -= 1;
            while (tape[ptr] != 0) {
                tape[ptr] -= 1;
                ptr += 1;
                tape[ptr] -= 1;
                ptr -= 1;
            }
            tape[ptr] += 1;
            ptr += 1;
            while (tape[ptr] != 0) {
                ptr -= 1;
                tape[ptr] -= 1;
                ptr += 1;
                while (tape[ptr] != 0) {
                    tape[ptr] -= 1;
                }
            }
            ptr -= 1;
            while (tape[ptr] != 0) {
                ptr += 1;
                tape[ptr] += 1;
                ptr -= 1;
                while (tape[ptr] != 0) {
                    tape[ptr] -= 1;
                }
            }
            tape[ptr] += 1;
            ptr += 1;
            while (tape[ptr] != 0) {
                ptr -= 1;
                tape[ptr] -= 1;
                ptr += 1;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0) {
                ptr -= 2;
                while (tape[ptr] != 0) {
                    ptr += 4;
                    tape[ptr] += 1;
                    ptr += 1;
                    tape[ptr] += 1;
                    ptr -= 5;
                    tape[ptr] -= 1;
                }
                ptr += 5;
                while (tape[ptr] != 0) {
                    ptr -= 5;
                    tape[ptr] += 1;
                    ptr += 5;
                    tape[ptr] -= 1;
                }
                ptr -= 1;
                while (tape[ptr] != 0) {
                    ptr -= 75;
                    tape[ptr] += 1;
                    ptr += 75;
                    tape[ptr] -= 1;
                }
                ptr -= 77;
                ptr += 2;
                while (tape[ptr] != 0) {
                    while (tape[ptr] != 0) {
                        ptr += 2;
                    }
                    tape[ptr] += 1;
                    while (tape[ptr] != 0) {
                        ptr -= 2;
                    }
                    ptr += 2;
                    tape[ptr] -= 1;
                }
                tape[ptr] += 1;
                while (tape[ptr] != 0) {
                    ptr += 2;
                }
                ptr -= 1;
                while (tape[ptr] != 0) {
                    ptr -= 1;
                    while (tape[ptr] != 0) {
                        ptr -= 2;
                    }
                    ptr += 1;
                    tape[ptr] += 1;
                    ptr -= 1;
                    ptr += 76;
                    tape[ptr] += 1;
                    ptr -= 76;
                    ptr += 2;
                    while (tape[ptr] != 0) {
                        ptr += 2;
                    }
                    ptr -= 1;
                    tape[ptr] -= 1;
                }
                ptr -= 1;
                while (tape[ptr] != 0) {
                    ptr -= 2;
                }
                ptr += 1;
                while (tape[ptr] != 0) {
                    ptr += 1;
                    while (tape[ptr] != 0) {
                        ptr += 2;
                    }
                    ptr -= 1;
                    tape[ptr] += 1;
                    ptr -= 1;
                    while (tape[ptr] != 0) {
                        ptr -= 2;
                    }
                    ptr += 1;
                    tape[ptr] -= 1;
                }
                ptr += 1;
                while (tape[ptr] != 0) {
                    ptr += 2;
                }
                ptr -= 2;
                while (tape[ptr] != 0) {
                    tape[ptr] -= 1;
                    ptr -= 2;
                }
                ptr += 76;
                printf("%c", tape[ptr]); // 2
                while (tape[ptr] != 0) {
                    tape[ptr] -= 1;
                }
                ptr -= 3;
                while (tape[ptr] != 0) {
                    ptr += 3;
                    tape[ptr] += 1;
                    ptr += 1;
                    tape[ptr] += 1;
                    ptr -= 4;
                    tape[ptr] -= 1;
                }
                ptr += 4;
                while (tape[ptr] != 0) {
                    ptr -= 4;
                    tape[ptr] += 1;
                    ptr += 4;
                    tape[ptr] -= 1;
                }
                tape[ptr] += 1;
                while (tape[ptr] != 0) {
                    ptr -= 1;
                    tape[ptr] += 1;
                    ptr += 1;
                    tape[ptr] -= 1;
                }
                ptr -= 4;
                while (tape[ptr] != 0) {
                    tape[ptr] -= 1;
                }
                ptr += 3;
                while (tape[ptr] != 0) {
                    ptr -= 3;
                    tape[ptr] += 1;
                    ptr += 3;
                    tape[ptr] -= 1;
                }
                ptr -= 1;
                while (tape[ptr] != 0) {
                    tape[ptr] -= 1;
                }
                ptr -= 1;
                tape[ptr] += 1;
                ptr += 1;
            }
            ptr -= 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0) {
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] -= 1;
    }
    ptr -= 3;
    while (tape[ptr] != 0) {
        ptr += 2;
        tape[ptr] += 1;
        ptr += 1;
        tape[ptr] += 1;
        ptr -= 3;
        tape[ptr] -= 1;
    }
    ptr += 3;
    while (tape[ptr] != 0) {
        ptr -= 3;
        tape[ptr] += 1;
        ptr += 3;
        tape[ptr] -= 1;
    }
    ptr -= 1;
    printf("%c", tape[ptr]); // 3
    while (tape[ptr] != 0) {
        tape[ptr] -= 1;
    }
}
